from __future__ import annotations

from pathlib import Path

DEFAULT_LLMROUTER_BASE_URL = "http://106.15.124.164:4000/v1"


def render_miniswe_config(
    save_path: Path,
    *,
    runtime: str = "docker",
    api_base: str = DEFAULT_LLMROUTER_BASE_URL,
) -> str:
    if runtime != "docker":
        raise ValueError("the current mini-SWE adapter provides its safe sandbox only with docker")
    if not api_base.startswith(("http://", "https://")):
        raise ValueError("api_base must be an HTTP(S) URL")
    return f'''# Generated by mls-lite-runner; contains no API key.
max_steps: 1000
max_tests: 3
save_path: "{save_path.as_posix()}"
data_root: vendor/data
seeds: [42, 123, 456]
container_runtime: docker
compute_scale: 1.0

miniswe_bash:
  environment:
    type: docker
    image: auto
    sandbox: true
    timeout: 120
    run_args: []
  agent:
    step_limit: 1000
    cost_limit: 0
    wall_time_limit_seconds: 18000
    max_consecutive_format_errors: 3
  model:
    model_class: litellm
    cost_tracking: ignore_errors
    model_kwargs:
      drop_params: true
      api_base: "{api_base}"
'''
